import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Layout from "../components/layaout";
import Search from "../components/search/search";
import { traslate } from "../i18";
import Link from "next/link";
import { Env } from "../class/env.class";
import { Category } from "../interfaces/category.interface";
import { GetStaticProps, GetStaticPropsResult } from "next";
import CategoryCard from "../components/category/category";
import Tittle from "../components/title/title";

interface Props {
  categories: Category[];
}

export default function Home({ categories }:Props) {
  return (
    <Layout>
      <Head>
        <title>LostInLondon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.banner}>
        <div className={styles.title}>
          <span>{traslate("titleInit")}</span>
          <span>{traslate("titleEnd")}</span>
          <Search />
        </div>
      </section>
      <section className={styles.categories}>
        {categories.map((category) => (
          <CategoryCard key={category._id} category={category} />
        ))}
      </section>
      <main className={styles.products}>
         <Tittle title={traslate("DEALS_OFFERS")}/>
      </main>
    </Layout>
  );
}

export async function getStaticProps(): Promise<GetStaticPropsResult<Props>> {
  const response = await fetch(`${Env.apiUrl}/categories`);
  const categories = (await response.json()) as Category[];
  return {
    props : {categories}
  }
}
