import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout from "../components/layaout";
import Search from "../components/search/search";
import { traslate } from "../i18";
import { Env } from "../class/env.class";
import { Category } from "../interfaces/category.interface";
import { GetStaticPropsResult } from "next";
import CategoryCard from "../components/category/category";
import Tittle from "../components/title/title";
import Sections from "../components/sections/sections";
import SubTittle from "../components/subtittle/subtitle";
import Swiper from "../components/swiper/swiper";
import { Service } from "../interfaces/services.interface";

interface Props {
  categories: Category[];
  services: Service[]
}

export default function Home({ categories ,services}:Props) {

  const sections = [
    "UPCOMING_FOOTBALL",
    "TOP_ATTRACTIONS",
    "GREAT_DESTINATIONS",
    "MOST_POPULAR_SHOWS",
  ].map((section) => traslate(section));
  return (
    <Layout>
      <Head>
        <title>LostInLondon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.banner}>
      <div className={styles.singAgent}>
          <Image
            src="/imagenes/login-agent.png"
            alt="login-agent"
            height={20}
            width={20}
          />
          <span>Agent Login</span>
        </div>
        <div className={styles.title}>
          <span>{traslate("titleInit")}</span>
          <span>{traslate("titleEnd")}</span>
          <Search />
        </div>
      </section>
      <section className={styles.categories}>
        {categories.map((category) => (
          <CategoryCard key={category._id} category={category} />
        ))}
      </section>
      <section className={styles.products}>
        <div className={styles.dealsTittle}>
          <Tittle title={traslate("DEALS_OFFERS")} />
          <Sections sections={sections} />
        </div>
        <div className={styles.swiperWhite}>
          <SubTittle subtitle={traslate("UPCOMING_FOOTBALL")} />
          <section className={styles.services}>
            <Swiper services={services} backGroundColorCard="#f1f1f1" />
          </section>
        </div>
        <div className={styles.swiperGray}>
          <SubTittle subtitle={traslate("TOP_ATTRACTIONS")} />
          <section className={styles.services}>
            <Swiper services={services} />
          </section>
        </div>
        <div className={styles.swiperWhite}>
          <SubTittle subtitle={traslate("GREAT_DESTINATIONS")} />
          <section className={styles.services}>
            <Swiper services={services} backGroundColorCard="#f1f1f1"/>
          </section>
        </div>
        <div className={styles.swiperGray}>
          <SubTittle subtitle={traslate("MOST_POPULAR_SHOWS")} />
          <section className={styles.services}>
            <Swiper services={services} />
          </section>
        </div>
      </section>
    </Layout>
  );
}

export async function getStaticProps(): Promise<GetStaticPropsResult<Props>> {
  const responseCategories = await fetch(`${Env.apiUrl}/categories`);
  const categories = (await responseCategories.json()) as Category[];
  const responseServices = await fetch("http://localhost:4500/services");
  const services = await responseServices.json() as Service[];
  return {
    props : {categories,services}
  }
}
